import type { ThemeCatalog } from "./types";

export const LOCAL_THEME_CATALOG = {
  schemaVersion: 1,
  themes: [
    {
      id: "hooandee-gallery",
      cssLoaderName: "Hooandee Gallery",
      nameKey: "themes.gallery.name",
      descriptionKey: "themes.gallery.description",
      availability: "available",
      author: "Hooandee",
      includedVersion: "0.7.8",
      cssLoaderManifestVersion: 9,
      minimumCssLoaderBackendVersion: 9,
      projectUrl: "https://github.com/Hooandee/hooandee-themes",
      tags: ["library", "gallery"],
      exclusiveGroup: "hooandee-system-theme",
      installSources: [
        {
          kind: "bundled",
          packageId: "hooandee-gallery",
        },
        {
          kind: "official-remote",
          channelId: "panel-pages-v1",
        },
      ],
      runtime: {
        moduleId: "gallery",
        surfaces: ["library", "library-grid", "game-details", "settings"],
        capabilities: ["surface-isolation", "performance-budget"],
      },
    },
    {
      id: "hooandee-shattered-realms",
      cssLoaderName: "Hooandee Shattered Realms",
      nameKey: "themes.shattered.name",
      descriptionKey: "themes.shattered.description",
      availability: "coming-soon",
      author: "Hooandee",
      cssLoaderManifestVersion: 9,
      minimumCssLoaderBackendVersion: 9,
      projectUrl: "https://github.com/Hooandee/hooandee-themes",
      tags: ["library", "fantasy"],
      exclusiveGroup: "hooandee-system-theme",
      installSources: [],
    },
    {
      id: "hooandee-obsidian-bloom",
      cssLoaderName: "Hooandee Obsidian Bloom",
      nameKey: "themes.obsidian.name",
      descriptionKey: "themes.obsidian.description",
      availability: "coming-soon",
      author: "Hooandee",
      cssLoaderManifestVersion: 9,
      minimumCssLoaderBackendVersion: 9,
      tags: ["experimental", "oled", "runtime"],
      exclusiveGroup: "hooandee-system-theme",
      installSources: [],
      runtime: {
        moduleId: "obsidian-bloom",
        surfaces: ["library", "library-grid", "game-details", "settings"],
        capabilities: [
          "orbital-library",
          "grid-motion",
          "adaptive-backdrop",
          "surface-styles",
          "details-transition",
          "settings-shell",
          "performance-budget",
        ],
      },
    },
  ],
} as const satisfies ThemeCatalog;
