import type { Lang } from "../i18n";

const ENGLISH: Readonly<Record<string, string>> = {
  "Color de acento": "Accent color",
  Apariencia: "Appearance",
  "Posición del nombre": "Name position",
  "Mostrar nombre del juego": "Show game title",
  "Mostrar tiempo jugado": "Show playtime",
  "Vista inicial de Detalles": "Initial Details view",
  "Profundidad del carrusel": "Carousel depth",
  "Tamaño de galería": "Gallery size",
  "Primera tarjeta": "First card",
  "Panel de cristal de Inicio": "Home glass panel",
  "Difuminado de parrilla": "Grid blur",
  "Difuminado de detalles": "Details blur",
  "Contenido del header": "Header content",
  "Indicadores del header": "Header indicators",
  "Estilo de batería": "Battery style",
  "Contenido del footer": "Footer content",
  "Estilo de iconos del footer": "Footer icon style",
  "Acento bioluminiscente": "Bioluminescent accent",
  "Densidad de parrilla": "Grid density",
  "Animaciones de parrilla": "Grid animations",
  "Intensidad de movimiento": "Motion intensity",
  "Fondo adaptativo": "Adaptive backdrop",
  "Escena de biblioteca": "Library scene",
  "Escena de parrilla": "Grid scene",
  "Transición al detalle": "Details transition",
  "Estilo de ajustes": "Settings style",
  "Modo de rendimiento": "Performance mode",
  "Dúo": "Duo",
  Glaciar: "Glacier",
  Salvia: "Sage",
  "Carmesí": "Crimson",
  Rosa: "Rose",
  Oscuro: "Dark",
  Claro: "Light",
  Arriba: "Top",
  Abajo: "Bottom",
  Completa: "Full",
  "Pequeño": "Small",
  Predeterminado: "Default",
  Grande: "Large",
  "Hero horizontal": "Horizontal hero",
  "Portada uniforme": "Uniform cover",
  Desactivado: "Off",
  Suave: "Soft",
  Medio: "Medium",
  Alto: "High",
  Completo: "Full",
  "Solo indicadores": "Indicators only",
  Oculto: "Hidden",
  "Batería y hora": "Battery and time",
  "Solo batería": "Battery only",
  "Solo hora": "Time only",
  "Cian": "Cyan",
  "Compacta": "Compact",
  "Cinemática": "Cinematic",
  "Galería": "Gallery",
  "Reducida": "Reduced",
  "Equilibrada": "Balanced",
  "Total": "Full",
  "Apagado": "Off",
  "Sutil": "Subtle",
  "Cinemático": "Cinematic",
  "Inmersivo": "Immersive",
  "Esencial": "Essential",
  "Atmosférica": "Atmospheric",
  "Inmersiva": "Immersive",
  "Directa": "Direct",
  "Órbita": "Orbit",
  "Constelación": "Constellation",
  "Abismo orbital": "Orbital Abyss",
  "Ninguna": "None",
  Ninguno: "None",
  "Fundido": "Fade",
  "Cristal": "Glass",
  "Cometa": "Comet",
};

const SPANISH: Readonly<Record<string, string>> = {
  Yes: "Sí",
};

const ITALIAN: Readonly<Record<string, string>> = {
  "Color de acento": "Colore accento",
  Apariencia: "Aspetto",
  "Posición del nombre": "Posizione del nome",
  "Mostrar nombre del juego": "Mostra titolo del gioco",
  "Mostrar tiempo jugado": "Mostra tempo di gioco",
  "Vista inicial de Detalles": "Vista iniziale dei dettagli",
  "Profundidad del carrusel": "Profondità del carosello",
  "Tamaño de galería": "Dimensione galleria",
  "Primera tarjeta": "Prima scheda",
  "Panel de cristal de Inicio": "Pannello in vetro della Home",
  "Difuminado de parrilla": "Sfocatura griglia",
  "Difuminado de detalles": "Sfocatura dettagli",
  "Contenido del header": "Contenuto intestazione",
  "Indicadores del header": "Indicatori intestazione",
  "Estilo de batería": "Stile batteria",
  "Contenido del footer": "Contenuto piè di pagina",
  "Estilo de iconos del footer": "Stile icone piè di pagina",
  "Acento bioluminiscente": "Accento bioluminescente",
  "Densidad de parrilla": "Densità griglia",
  "Animaciones de parrilla": "Animazioni griglia",
  "Intensidad de movimiento": "Intensità movimento",
  "Fondo adaptativo": "Sfondo adattivo",
  "Escena de biblioteca": "Scena libreria",
  "Escena de parrilla": "Scena griglia",
  "Transición al detalle": "Transizione ai dettagli",
  "Estilo de ajustes": "Stile impostazioni",
  "Modo de rendimiento": "Modalità prestazioni",
  "Dúo": "Duo",
  Glaciar: "Ghiacciaio",
  Salvia: "Salvia",
  "Carmesí": "Cremisi",
  Rosa: "Rosa",
  Oscuro: "Scuro",
  Claro: "Chiaro",
  Arriba: "In alto",
  Abajo: "In basso",
  Completa: "Completa",
  "Pequeño": "Piccola",
  Predeterminado: "Predefinita",
  Grande: "Grande",
  "Hero horizontal": "Hero orizzontale",
  "Portada uniforme": "Copertina uniforme",
  Desactivado: "Disattivato",
  Suave: "Leggero",
  Medio: "Medio",
  Alto: "Alto",
  Completo: "Completo",
  "Solo indicadores": "Solo indicatori",
  Oculto: "Nascosto",
  "Batería y hora": "Batteria e ora",
  "Solo batería": "Solo batteria",
  "Solo hora": "Solo ora",
  "Cian": "Ciano",
  Compacta: "Compatta",
  "Cinemática": "Cinematica",
  "Galería": "Galleria",
  Reducida: "Ridotta",
  Equilibrada: "Bilanciata",
  Total: "Completa",
  Apagado: "Spento",
  Sutil: "Sottile",
  "Cinemático": "Cinematico",
  Inmersivo: "Immersivo",
  Esencial: "Essenziale",
  "Atmosférica": "Atmosferica",
  Inmersiva: "Immersiva",
  Directa: "Diretta",
  "Órbita": "Orbita",
  "Constelación": "Costellazione",
  "Abismo orbital": "Abisso orbitale",
  Ninguna: "Nessuna",
  Ninguno: "Nessuno",
  Fundido: "Dissolvenza",
  Cristal: "Vetro",
  Cometa: "Cometa",
  Yes: "Sì",
};

export function presentThemePatchText(raw: string, lang: Lang): string {
  const dictionary = lang === "en" ? ENGLISH : lang === "it" ? ITALIAN : SPANISH;
  return dictionary[raw] ?? raw;
}
