// <auto-generated> scripts/export_design_tokens.py from shared/design/tokens.json </auto-generated>
namespace PanelDeControl.Core.Presentation;

public static partial class AccentPalette
{
    public const string DefaultId = "blue";

    public static IReadOnlyList<AccentColor> All { get; } = new[]
    {
        new AccentColor("blue", 0xFF4EA1FFu),
        new AccentColor("sky", 0xFF38BDF8u),
        new AccentColor("cyan", 0xFF22B8E0u),
        new AccentColor("teal", 0xFF22C7C0u),
        new AccentColor("mint", 0xFF34D399u),
        new AccentColor("green", 0xFF3FBF6Fu),
        new AccentColor("lime", 0xFFA3D43Fu),
        new AccentColor("yellow", 0xFFF5C542u),
        new AccentColor("amber", 0xFFE0952Au),
        new AccentColor("orange", 0xFFF2683Cu),
        new AccentColor("red", 0xFFE5484Du),
        new AccentColor("rose", 0xFFFB7185u),
        new AccentColor("pink", 0xFFEC5C9Du),
        new AccentColor("fuchsia", 0xFFD946EFu),
        new AccentColor("purple", 0xFF9B7BF0u),
        new AccentColor("indigo", 0xFF6366F1u),
    };
}
