#!/usr/bin/env python3
"""Export the Linux design tokens for the Windows widget.

    python3 scripts/export_design_tokens.py          # rewrite the generated files
    python3 scripts/export_design_tokens.py --check  # exit 1 when any file is stale
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
THEME = ROOT / "src" / "theme.ts"
ACCENTS = ROOT / "src" / "system" / "accentColor.ts"
TOKENS = ROOT / "shared" / "design" / "tokens.json"
XAML = ROOT / "windows" / "src" / "PanelDeControl.GameBar" / "Theme" / "PdcTokens.xaml"
PALETTE = ROOT / "windows" / "src" / "PanelDeControl.Core" / "Presentation" / "AccentPalette.g.cs"
SCHEMA_VERSION = 1

WINDOWS = {
    "font_family": "Segoe UI Variable",
    "radius": {"card": 14, "tile": 10, "control": 6, "pill": 999},
}


def _object_body(source, name):
    match = re.search(r"const " + name + r" = \{(.*?)\n\}", source, re.S)
    if not match:
        raise SystemExit(f"{name} not found in {THEME.relative_to(ROOT)}")
    return match.group(1)


def _numbers(source, name):
    match = re.search(r"const " + name + r" = \{([^}]*)\}", source)
    if not match:
        raise SystemExit(f"{name} not found in {THEME.relative_to(ROOT)}")
    return {key: int(value) for key, value in re.findall(r"(\w+):\s*(\d+)", match.group(1))}


def _argb(value):
    value = value.strip()
    hex_match = re.fullmatch(r"#([0-9a-fA-F]{6})", value)
    if hex_match:
        return "#FF" + hex_match.group(1).upper()
    rgba = re.fullmatch(r"rgba\((\d+),\s*(\d+),\s*(\d+),\s*([0-9.]+)\)", value)
    if rgba:
        red, green, blue = (int(rgba.group(index)) for index in (1, 2, 3))
        alpha = round(float(rgba.group(4)) * 255)
        return f"#{alpha:02X}{red:02X}{green:02X}{blue:02X}"
    raise SystemExit(f"unsupported colour literal: {value}")


def build_tokens():
    theme = THEME.read_text(encoding="utf-8")
    colors = {
        name: _argb(value)
        for name, value in re.findall(r"^\s{2}(\w+):\s*\"([^\"]+)\",", _object_body(theme, "color"), re.M)
    }
    accents_source = ACCENTS.read_text(encoding="utf-8")
    accents = [
        {"id": accent_id, "color": _argb(hex_value)}
        for accent_id, hex_value in re.findall(r'\{ id: "(\w+)", hex: "(#[0-9a-fA-F]{6})" \}', accents_source)
    ]
    if not accents:
        raise SystemExit(f"no accents found in {ACCENTS.relative_to(ROOT)}")
    return {
        "schema_version": SCHEMA_VERSION,
        "source": ["src/theme.ts", "src/system/accentColor.ts"],
        "color": colors,
        "accents": accents,
        "default_accent": accents[0]["id"],
        "radius": _numbers(theme, "radius"),
        "space": _numbers(theme, "space"),
        "font": _numbers(theme, "font"),
        "windows": WINDOWS,
    }


def _pascal(name):
    return name[0].upper() + name[1:]


def render_tokens(tokens):
    return json.dumps(tokens, indent=2, sort_keys=True) + "\n"


def render_xaml(tokens):
    default_accent = next(item["color"] for item in tokens["accents"] if item["id"] == tokens["default_accent"])
    lines = [
        '<ResourceDictionary',
        '    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"',
        '    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">',
        "    <!-- Generated by scripts/export_design_tokens.py from shared/design/tokens.json. -->",
    ]
    for name, value in sorted(tokens["color"].items()):
        lines.append(f'    <Color x:Key="Pdc{_pascal(name)}Color">{value}</Color>')
    lines.append(f'    <Color x:Key="PdcAccentColor">{default_accent}</Color>')
    for name in sorted(tokens["color"]):
        lines.append(f'    <SolidColorBrush x:Key="Pdc{_pascal(name)}Brush" Color="{{StaticResource Pdc{_pascal(name)}Color}}" />')
    lines.append('    <SolidColorBrush x:Key="PdcAccentBrush" Color="{StaticResource PdcAccentColor}" />')
    for name, value in sorted(tokens["windows"]["radius"].items()):
        lines.append(f'    <CornerRadius x:Key="PdcRadius{_pascal(name)}">{value}</CornerRadius>')
    for name, value in sorted(tokens["space"].items()):
        lines.append(f'    <x:Double x:Key="PdcSpace{_pascal(name)}">{value}</x:Double>')
    for name, value in sorted(tokens["font"].items()):
        lines.append(f'    <x:Double x:Key="PdcFont{_pascal(name)}">{value}</x:Double>')
    lines.append(f'    <FontFamily x:Key="PdcFontFamily">{tokens["windows"]["font_family"]}</FontFamily>')
    lines.append("</ResourceDictionary>")
    return "\n".join(lines) + "\n"


def render_palette(tokens):
    entries = "\n".join(
        f'        new AccentColor("{item["id"]}", 0x{item["color"][1:]}u),' for item in tokens["accents"]
    )
    return (
        "// <auto-generated> scripts/export_design_tokens.py from shared/design/tokens.json </auto-generated>\n"
        "namespace PanelDeControl.Core.Presentation;\n\n"
        "public static partial class AccentPalette\n"
        "{\n"
        f'    public const string DefaultId = "{tokens["default_accent"]}";\n\n'
        "    public static IReadOnlyList<AccentColor> All { get; } = new[]\n"
        "    {\n"
        f"{entries}\n"
        "    };\n"
        "}\n"
    )


def outputs():
    tokens = build_tokens()
    return {TOKENS: render_tokens(tokens), XAML: render_xaml(tokens), PALETTE: render_palette(tokens)}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    stale = []
    for path, content in outputs().items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current == content:
            continue
        if args.check:
            stale.append(str(path.relative_to(ROOT)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    if stale:
        print("stale design tokens: " + ", ".join(stale) + f"; run {Path(__file__).name}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
